import Head from 'next/head'





export default function Home() {
  return (
    <div className= "App">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          
    <h1>Bonjour</h1>
    </div>
  )
}
